/*
 * Medida Challenge API
 *
 * This is the API that must be implemented as a your output deliverable of this challenge
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: challenges@medida.com
 * Generated by: https://openapi-generator.tech
 */


using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace ACMESportsAPI.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class EventsRequest
    {
        /// <summary>
        /// Gets or Sets League
        /// </summary>
        [Required]
        [JsonPropertyName("league")]
        public LeagueEnum League { get; set; }

        /// <summary>
        /// Gets or Sets StartDate
        /// </summary>
        [Required]
        [JsonPropertyName("startDate")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or Sets EndDate
        /// </summary>
        [Required]
        [JsonPropertyName("endDate")]
        public DateTime EndDate { get; set; }


    }
}
