/*
 * Medida Challenge API
 *
 * This is the API that must be implemented as a your output deliverable of this challenge
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: challenges@medida.com
 * Generated by: https://openapi-generator.tech
 */


using System.Text.Json.Serialization;
using System.Runtime.Serialization;

namespace ACMESportsAPI.Models
{
    /// <summary>
    /// Gets or Sets LeagueEnum
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum LeagueEnum
        {
            
            /// <summary>
            /// Enum NFLEnum for NFL
            /// </summary>
            [EnumMember(Value = "NFL")]
            NFL = 1
        }
}
